# Numpy array 합치기(2차원 행렬에서)
- np.c_ : column 을 가로로 붙일 때
- np.r_ : row 를 세로로 붙일 때
- 참조: https://stackoverflow.com/questions/8486294/how-do-i-add-an-extra-column-to-a-numpy-array

In [2]:
#1. np.c_
import numpy as np
n = 3
a = np.eye(n)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np.c_[a,np.ones(n)]

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 1.]])

In [6]:
#2. np.r_
np.r_[a, [a[1]]]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [18]:
# 차원 바꾸기
a = np.arange(16)
a.reshape(4,4), np.resize(a,(2,8)), a.reshape(-1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [16]:
a.ravel(), a.flatten()

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

data.tolist() 와 list(data) 의 차이
- data.tolist()를 사용하면 list 내부가 모두 list로 바뀌지만: 전체 리스트화
- list(data)를 사용하면 가장 밖의 모양(차원)만 list로 변할 뿐 내부는 numpy array로 유지되고 바뀌지 않는다: 껍데기만 리스트화

In [19]:
data = np.array([[1, 2, 3], [4, 5, 6]])
data.tolist(), list(data)

([[1, 2, 3], [4, 5, 6]], [array([1, 2, 3]), array([4, 5, 6])])

In [22]:
type(data.tolist()[0]), type(list(data)[0])

(list, numpy.ndarray)

Pandas나 Numpy 둘다 .astype으로 데이터타입 변경

In [26]:
datas = data.astype('str')
datas

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U11')

In [29]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3])
print(arr2 * 2)
print(1 / (arr2.mean() ** 2))
print(arr1 > 20)
# print(arr1 - arr2) 덧셈, 뺄셈은 broadcast 안됨

[2 4 6]
0.25
[False False  True  True]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 