# Numpy array 합치기(2차원 행렬에서)
- np.c_ : column 을 가로로 붙일 때
- np.r_ : row 를 세로로 붙일 때
- 참조: https://stackoverflow.com/questions/8486294/how-do-i-add-an-extra-column-to-a-numpy-array

In [1]:
#1. np.c_
import numpy as np
n = 3
a = np.eye(n)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [2]:
np.c_[a,np.ones(n)]

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 1.]])

In [6]:
#2. np.r_
np.r_[a, [a[1]]]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])